# Generated by Django 5.1.8 on 2026-07-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0120_backfill_score_tracer_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttsvoice',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='ttsvoice',
            name='workspace',
        ),
        migrations.DeleteModel(
            name='EvalSummaryTemplate',
        ),
        migrations.DeleteModel(
            name='TTSVoice',
        ),
    ]
