# Generated by Django 5.1.8 on 2026-07-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0095_merge_20260722_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardwidget',
            name='dashboard',
        ),
        migrations.RemoveField(
            model_name='dashboardwidget',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='imagineanalysis',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='imagineanalysis',
            name='project',
        ),
        migrations.RemoveField(
            model_name='imagineanalysis',
            name='saved_view',
        ),
        migrations.RemoveField(
            model_name='savedview',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='savedview',
            name='project',
        ),
        migrations.RemoveField(
            model_name='savedview',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='savedview',
            name='workspace',
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
        migrations.DeleteModel(
            name='DashboardWidget',
        ),
        migrations.DeleteModel(
            name='ImagineAnalysis',
        ),
        migrations.DeleteModel(
            name='SavedView',
        ),
    ]
