# Generated by Django 5.1.8 on 2026-07-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0027_retire_legacy_license_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeploymentTelemetryHeartbeat',
        ),
        migrations.DeleteModel(
            name='DeploymentTelemetryInstance',
        ),
    ]
